spring.application.name=sba301-lab03-employee-management
server.address=127.0.0.1
server.port=${SERVER_PORT:8083}
spring.jackson.deserialization.fail-on-unknown-properties=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
